server:
  port: 8081
  servlet:
    context-path: /joolemarketplace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/joole_marketplace?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: takeyuki.oshima
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
